version: '3'

services:
  app:
    build: .
    depends_on:
      - "postgres"
    ports:
      - "8000:8000"
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      TZ: "Asia/Tokyo"
    expose:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:bullseye
    expose:
      - "6379"
  nginx:
    image: nginx:mainline
    depends_on:
      - "app"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    
volumes:
  postgres: