version: "3"

services: 
    app: 
        build: . 
        tty: true
        ports:
            - "8080:8080"
        env_file: go.env
        volumes:
            - ./src:/go/src/app:cached

    postgres:
        image: postgres:latest
        restart: always
        env_file: db.env
        ports:
        - 5432:5432

    redis:
        image: "redis:latest"
        ports:
        - 6379:6379