version: '3'

services:
  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
  postgres:
    image: postgres:latest
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5    
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      TZ: "Asia/Tokyo"
    expose:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:bullseye
    expose:
      - "6379"
  nginx:
    image: nginx:mainline
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    
volumes:
  postgres: