name: Deploy
on:
  push:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.17.1"
      - run: go build -o main
      - name: Deploy to Server
        uses: horochx/deploy-via-scp@master
        with:
          local: src/main # eg: dist/*
          remote: ${{ secrets.TARGET }} # eg: /home/github-action/www
          host: ${{ secrets.REMOTE_HOST }} # eg: example.com
          port: ${{ secrets.REMOTE_PORT }} # eg: 22
          user: ${{ secrets.REMOTE_USER }} # eg: github-action
          key: ${{ secrets.SSH_PRIVATE_KEY }} # eg: -----BEGIN OPENSSH PRIVATE KEY-----\nHEIiyzh5cT7hN...
